engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 01f18be6d5b24c175bc1d07ce710c8ca
    - c3612ef84cdcab022fa842656771a1ea
    - 1554a0fcc268fd489b81acdb5e4ba7d4
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
    checks:
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "src/**"
exclude_paths:
- "benchmark/"
- "build/"
- "examples/"
- "tests/"
- "vendor/"
- "LICENSE"
- "**.md"
- "**.json"
- "**.lock"
- "**.xml"
- "**.yml"
