# .scrutinizer.yml

build:
    tests:
        override:
            - phpcs-run

checks:
    php: true

filter:
    paths:
        - "src/*"
    excluded_paths:
        - "examples/"
        - "tests/"
        - "vendor/"
        - "tmp/"