language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

addons:
    code_climate:
        repo_token: 5cdde67b5f4f9e1cebf8d32911c255a51ca829e3a5a80da3fe0300d029aa8f98

before_script: 
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: 
  - mkdir -p tmp
  - phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml tests

after_success:
  - travis_retry php vendor/bin/coveralls -v
  - vendor/bin/test-reporter

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

notifications:
  email:
    on_success: never
    on_failure: always